<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bPMN" nsURI="http://www.example.org/bPMN" nsPrefix="bPMN2RDP">
  <eClassifiers xsi:type="ecore:EClass" name="Named" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowobject" upperBound="-1"
        eType="#//FlowObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//Link"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowObject" abstract="true" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLink" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingoingLink" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//FlowObject"
        eOpposite="#//FlowObject/outgoingLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//FlowObject" eOpposite="#//FlowObject/ingoingLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//FlowObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//FlowObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TaskType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" abstract="true" eSuperTypes="#//FlowObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//GatewayType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaskType">
    <eLiterals name="manual"/>
    <eLiterals name="utilisateur" value="1"/>
    <eLiterals name="service" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="start"/>
    <eLiterals name="intermédiate" value="1"/>
    <eLiterals name="end" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GatewayType">
    <eLiterals name="exclusive"/>
    <eLiterals name="inclusive" value="1"/>
    <eLiterals name="parallel" value="2"/>
    <eLiterals name="complex" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkGateway" eSuperTypes="#//Gateway"/>
</ecore:EPackage>
